FROM registry.access.redhat.com/ubi8:8.10-1020

RUN dnf update -y && dnf install -y \
  bzip2 \
  curl \
  findutils \
  gcc-c++ \
  gcc-gfortran \
  git \
  gnupg2 \
  hostname \
  iproute \
  redhat-lsb-core \
  python3 \
  python3-pip \
  python3-setuptools \
  sudo \
  unzip \
  xauth \
  xz
